<?php
/** @var \Magestore\Bannerslider\Block\SliderItem $block */
$styleSlide = $block->getSlider()->getStyleSlide();
$slider = $block->getSlider();
$htmlId   = $block->getFlexsliderHtmlId();
$bannerCollection = $block->getBannerCollection();
?>
<!-- LiveWise slider will go here -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.0.1/TweenMax.min.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('Magestore_Bannerslider::css/livewise.css')?>">
<div class="magestore-bannerslider-standard"
     data-mage-init='{"magestore/impress": {"url": "<?php echo $this->getUrl("bannerslider/index/impress") ?>", "slider_id": "<?php echo $block->getSlider()->getId() ?>"}}'>
    <div class="magestore-bannerslide-livewise">
        <div id="<?php echo $htmlId ?>"
             class="bannerslide-livewise bannerslide-livewise-content-image <?php echo $htmlId ?>">
            <?php foreach ($bannerCollection as $banner): ?>
                <div class="slide">
                    <a href="<?php echo $banner->getClickUrl() ?>"
                       target="<?php echo $banner->getTargetValue() ?>"
                       data-mage-init='{"magestore/clickbanner": {"url": "<?php echo $this->getUrl("bannerslider/index/click") ?>", "slider_id": "<?php echo $banner->getSliderId() ?>", "banner_id": "<?php echo $banner->getId() ?>" }}' >
                        <img alt="<?php echo $banner->getImageAlt() ?>"
                             src="<?php echo $block->getBannerImageUrl($banner) ?>"/>
                    </a>
                </div>
            <?php endforeach ?>
        </div>
    </div>
</div>
<script type="text/javascript">
 (function () {
     require(['jquery', 'magestore/livewise'], function($) {
         var bannerdivid = "<?php echo $htmlId ?>";
         var banner_width = 1280;
         var banner_height = 640;
         $('#' + bannerdivid).buildBannersliderLivewise({
             width: banner_width,
             height: banner_height
         });
     });
 })();
</script>
