<?php
/** @var \Magestore\Bannerslider\Block\SliderItem $block */
$styleSlide = $block->getSlider()->getStyleSlide();
$slider = $block->getSlider();
$htmlId = $block->getFlexsliderHtmlId();
$bannerCollection = $block->getBannerCollection();
$repeat = count($bannerCollection) <= 2 ? 3 : 2;
?>
<!-- LiveWise slider will go here -->
<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('Magestore_Bannerslider::css/livewise.css')?>">
<div class="magestore-bannerslider-standard"
     data-mage-init='{"magestore/impress": {"url": "<?php echo $this->getUrl("bannerslider/index/impress") ?>", "slider_id": "<?php echo $block->getSlider()->getId() ?>"}}'>
    <div class="magestore-bannerslide-livewise">
        <div id="<?php echo $htmlId ?>"
             class="bannerslide-livewise <?php echo $htmlId ?>">
            <div class="slides-container">
                <?php for ($i = 0; $i < $repeat; $i++) { ?>
                <?php foreach ($bannerCollection as $banner): ?>
                    <div class="slide"
                         style="background: url(<?php echo $block->getBannerImageUrl($banner) ?>)">
                        <div class="picture">
                            <a href="<?php echo $banner->getClickUrl() ?>"
                               target="<?php echo $banner->getTargetValue() ?>"
                               data-mage-init='{"magestore/clickbanner": {"url": "<?php echo $this->getUrl("bannerslider/index/click") ?>", "slider_id": "<?php echo $banner->getSliderId() ?>", "banner_id": "<?php echo $banner->getId() ?>" }}' >
                                <img alt="<?php echo $banner->getImageAlt() ?>"
                                     src="<?php echo $block->getBannerImageUrl($banner) ?>"/>
                            </a>
                        </div>
                    </div>
                <?php endforeach ?>
                <?php } ?>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
 (function () {
     require([
         'jquery',
         'GSAP/TimelineMax',
         'GSAP/TweenMax',
         'magestore/livewise'
     ], function($, TimelineMax, TweenMax) {
         var _start_bannerslide = function() {
             var banner_width = $('.magestore-bannerslider-standard').outerWidth();
             var banner_height = banner_width * 0.5;
             console.log('liyuhk', $('.magestore-bannerslider-standard').outerWidth());
             var bannerdiv = $('#'+'<?php echo $htmlId ?>');
             $(bannerdiv).css({
                 width: ''+banner_width+'px',
                 height: ''+banner_height+'px'
             });
             $('.slides-container', bannerdiv).buildBannersliderLivewise({
                 width: banner_width,
                 height: banner_height
             });
         }
         _start_bannerslide();
         $(window).on('orientationchange', function(event) {
             setTimeout(function() {
                 _start_bannerslide();
             }, 100);
         });
     });
 })();
</script>
